apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::988024294104:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GSSK4XOUWTX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-07T14:06:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2159"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 68b4a083-a9d2-4ff3-826c-b68db8b3a2bc
